# Generated by Django 4.2.4 on 2023-08-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acount',
            old_name='user_name',
            new_name='username',
        ),
    ]
