# Generated by Django 4.2.4 on 2023-09-23 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0002_coupons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupons",
            name="user",
        ),
    ]
