# Generated by Django 4.2.4 on 2023-09-23 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_remove_coupons_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
