# Generated by Django 4.2.4 on 2023-09-23 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0005_remove_coupons_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupons",
            name="user",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
