# Generated by Django 4.2.4 on 2023-10-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0013_acount_referal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referal_code",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
