# Generated by Django 4.2.4 on 2023-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0018_wallet_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acount",
            name="wallet_money",
        ),
    ]
