# Generated by Django 4.2.4 on 2023-10-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0019_remove_acount_wallet_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
