# Generated by Django 4.2.4 on 2023-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0021_rename_timestamp_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acount",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
