# Generated by Django 4.2.4 on 2023-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
