# Generated by Django 4.2.4 on 2023-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_usercoupons_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercoupons",
            old_name="apllied",
            new_name="applied",
        ),
    ]
