# Generated by Django 4.2.4 on 2023-10-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_details_status_alter_order_details_grand_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reason_for_cancellation",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
